# Import necessary Lib's

In [360]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [361]:
match_data = pd.read_csv("dataset/match_data.csv")

/tmp/ipykernel_5820/2789249824.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  match_data = pd.read_csv("dataset/match_data.csv")

In [362]:
match_info = pd.read_csv("dataset/match_info_data.csv")

In [363]:
match_info.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1370353,2023,Ahmedabad,2023/05/29,Gujarat Titans,Chennai Super Kings,Chennai Super Kings,field,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
1,1370352,2023,Ahmedabad,2023/05/26,Gujarat Titans,Mumbai Indians,Mumbai Indians,field,normal,0,Gujarat Titans,62,0,Shubman Gill,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,J Madanagopal
2,1370351,2023,Chennai,2023/05/24,Mumbai Indians,Lucknow Super Giants,Mumbai Indians,bat,normal,0,Mumbai Indians,81,0,Akash Madhwal,"MA Chidambaram Stadium, Chepauk, Chennai",BNJ Oxenford,VK Sharma,CB Gaffaney
3,1370350,2023,Chennai,2023/05/23,Chennai Super Kings,Gujarat Titans,Gujarat Titans,field,normal,0,Chennai Super Kings,15,0,RD Gaikwad,"MA Chidambaram Stadium, Chepauk, Chennai",AK Chaudhary,CB Gaffaney,BNJ Oxenford
4,1359543,2023,Mumbai,2023/05/21,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,C Green,"Wankhede Stadium, Mumbai",KN Ananthapadmanabhan,RJ Tucker,R Pandit

In [364]:
match_info.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [365]:
match_info['match_id'] = match_info['id']
match_info = match_info.drop(columns=["id"])
match_info.head()

,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id
0,2023,Ahmedabad,2023/05/29,Gujarat Titans,Chennai Super Kings,Chennai Super Kings,field,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,1370353
1,2023,Ahmedabad,2023/05/26,Gujarat Titans,Mumbai Indians,Mumbai Indians,field,normal,0,Gujarat Titans,62,0,Shubman Gill,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,J Madanagopal,1370352
2,2023,Chennai,2023/05/24,Mumbai Indians,Lucknow Super Giants,Mumbai Indians,bat,normal,0,Mumbai Indians,81,0,Akash Madhwal,"MA Chidambaram Stadium, Chepauk, Chennai",BNJ Oxenford,VK Sharma,CB Gaffaney,1370351
3,2023,Chennai,2023/05/23,Chennai Super Kings,Gujarat Titans,Gujarat Titans,field,normal,0,Chennai Super Kings,15,0,RD Gaikwad,"MA Chidambaram Stadium, Chepauk, Chennai",AK Chaudhary,CB Gaffaney,BNJ Oxenford,1370350
4,2023,Mumbai,2023/05/21,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,C Green,"Wankhede Stadium, Mumbai",KN Ananthapadmanabhan,RJ Tucker,R Pandit,1359543

In [366]:
match_data.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id
0,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
1,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.2,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
2,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.3,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
3,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.4,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
4,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.5,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353

In [367]:
df = match_data.merge(match_info,on="match_id")

In [368]:
df.head()

,match_id,season_x,start_date,venue_x,innings,ball,batting_team,bowling_team,striker,non_striker,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue_y,umpire1,umpire2,umpire3
0,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
1,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.2,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
2,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.3,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
3,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.4,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
4,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.5,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan

In [369]:
#with open("merged_data.csv","w") as f:
    #df.to_csv(f)

In [370]:
df.shape

(243817, 40)

In [371]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243817 entries, 0 to 243816
Data columns (total 40 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   match_id                243817 non-null  int64
 1   season_x                243817 non-null  object
 2   start_date              243817 non-null  object
 3   venue_x                 243817 non-null  object
 4   innings                 243817 non-null  int64
 5   ball                    243817 non-null  float64
 6   batting_team            243817 non-null  object
 7   bowling_team            243817 non-null  object
 8   striker                 243817 non-null  object
 9   non_striker             243817 non-null  object
 10  bowler                  243817 non-null  object
 11  runs_off_bat            243817 non-null  int64
 12  extras                  243817 non-null  int64
 13  wides                   7652 non-null    float64
 14  noballs                 1018 non-null    float64
 15  byes                    628 non-null     float64
 16  legbyes                 3778 non-null    float64
 17  penalty                 2 non-null       float64
 18  wicket_type             12067 non-null   object
 19  player_dismissed        12067 non-null   object
 20  other_wicket_type       0 non-null       float64
 21  other_player_dismissed  0 non-null       float64
 22  cricsheet_id            243817 non-null  int64
 23  season_y                243817 non-null  object
 24  city                    231420 non-null  object
 25  date                    243817 non-null  object
 26  team1                   243817 non-null  object
 27  team2                   243817 non-null  object
 28  toss_winner             243817 non-null  object
 29  toss_decision           243817 non-null  object
 30  result                  243817 non-null  object
 31  dl_applied              243817 non-null  int64
 32  winner                  239693 non-null  object
 33  win_by_runs             243817 non-null  int64
 34  win_by_wickets          243817 non-null  int64
 35  player_of_match         243327 non-null  object
 36  venue_y                 243817 non-null  object
 37  umpire1                 243817 non-null  object
 38  umpire2                 243817 non-null  object
 39  umpire3                 243128 non-null  object
dtypes: float64(8), int64(8), object(24)
memory usage: 74.4+ MB

In [372]:
df.isnull().sum()

match_id                       0
season_x                       0
start_date                     0
venue_x                        0
innings                        0
ball                           0
batting_team                   0
bowling_team                   0
striker                        0
non_striker                    0
bowler                         0
runs_off_bat                   0
extras                         0
wides                     236165
noballs                   242799
byes                      243189
legbyes                   240039
penalty                   243815
wicket_type               231750
player_dismissed          231750
other_wicket_type         243817
other_player_dismissed    243817
cricsheet_id                   0
season_y                       0
city                       12397
date                           0
team1                          0
team2                          0
toss_winner                    0
toss_decision                  0
result                         0
dl_applied                     0
winner                      4124
win_by_runs                    0
win_by_wickets                 0
player_of_match              490
venue_y                        0
umpire1                        0
umpire2                        0
umpire3                      689
dtype: int64

In [373]:
df.wides.value_counts()

wides
1.0    6998
2.0     312
5.0     280
3.0      55
4.0       7
Name: count, dtype: int64

In [374]:
df.wides = df.wides.fillna(0)

In [375]:
df.byes.value_counts()

byes
1.0    420
4.0    167
2.0     38
3.0      3
Name: count, dtype: int64

In [376]:
df.byes = df.byes.fillna(0)

In [377]:
df.legbyes.value_counts()

legbyes
1.0    3271
4.0     304
2.0     177
3.0      22
5.0       4
Name: count, dtype: int64

In [378]:
df.legbyes = df.legbyes.fillna(0)

In [379]:
df.penalty.value_counts()

penalty
5.0    2
Name: count, dtype: int64

In [380]:
df.noballs.value_counts()

noballs
1.0    1002
2.0       9
5.0       6
3.0       1
Name: count, dtype: int64

In [381]:
df.noballs = df.noballs.fillna(0)

In [382]:
df = df.drop(columns=["penalty"])

In [383]:
df.isnull().sum()

match_id                       0
season_x                       0
start_date                     0
venue_x                        0
innings                        0
ball                           0
batting_team                   0
bowling_team                   0
striker                        0
non_striker                    0
bowler                         0
runs_off_bat                   0
extras                         0
wides                          0
noballs                        0
byes                           0
legbyes                        0
wicket_type               231750
player_dismissed          231750
other_wicket_type         243817
other_player_dismissed    243817
cricsheet_id                   0
season_y                       0
city                       12397
date                           0
team1                          0
team2                          0
toss_winner                    0
toss_decision                  0
result                         0
dl_applied                     0
winner                      4124
win_by_runs                    0
win_by_wickets                 0
player_of_match              490
venue_y                        0
umpire1                        0
umpire2                        0
umpire3                      689
dtype: int64

In [384]:
df.wicket_type.value_counts()

wicket_type
caught                   7437
bowled                   2089
run out                  1062
lbw                       750
caught and bowled         349
stumped                   345
hit wicket                 15
retired hurt               15
retired out                 3
obstructing the field       2
Name: count, dtype: int64

In [385]:
df.wicket_type = df.wicket_type.fillna("none")

In [386]:
df.wicket_type.value_counts()

wicket_type
none                     231750
caught                     7437
bowled                     2089
run out                    1062
lbw                         750
caught and bowled           349
stumped                     345
hit wicket                   15
retired hurt                 15
retired out                   3
obstructing the field         2
Name: count, dtype: int64

In [387]:
df = df.drop(columns=["player_dismissed","other_player_dismissed","other_wicket_type","city"])

In [388]:
df.isnull().sum()

match_id              0
season_x              0
start_date            0
venue_x               0
innings               0
ball                  0
batting_team          0
bowling_team          0
striker               0
non_striker           0
bowler                0
runs_off_bat          0
extras                0
wides                 0
noballs               0
byes                  0
legbyes               0
wicket_type           0
cricsheet_id          0
season_y              0
date                  0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
result                0
dl_applied            0
winner             4124
win_by_runs           0
win_by_wickets        0
player_of_match     490
venue_y               0
umpire1               0
umpire2               0
umpire3             689
dtype: int64

In [389]:
df

,match_id,season_x,start_date,venue_x,innings,ball,batting_team,bowling_team,striker,non_striker,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue_y,umpire1,umpire2,umpire3
0,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
1,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.2,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
2,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.3,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
3,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.4,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
4,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.5,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243812,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,2,14.5,Royal Challengers Bangalore,Kolkata Knight Riders,P Kumar,SB Joshi,...,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba
243813,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,2,14.6,Royal Challengers Bangalore,Kolkata Knight Riders,SB Joshi,P Kumar,...,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba
243814,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,2,14.7,Royal Challengers Bangalore,Kolkata Knight Riders,P Kumar,SB Joshi,...,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba
243815,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,2,15.1,Royal Challengers Bangalore,Kolkata Knight Riders,SB Joshi,P Kumar,...,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba
243816,335982,2007/08,2008-04-18,M Chinnaswamy Stadium,2,15.2,Royal Challengers Bangalore,Kolkata Knight Riders,SB Joshi,P Kumar,...,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,AM Saheba

In [390]:
df.columns

Index(['match_id', 'season_x', 'start_date', 'venue_x', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'wicket_type', 'cricsheet_id', 'season_y', 'date', 'team1', 'team2',
       'toss_winner', 'toss_decision', 'result', 'dl_applied', 'winner',
       'win_by_runs', 'win_by_wickets', 'player_of_match', 'venue_y',
       'umpire1', 'umpire2', 'umpire3'],
      dtype='object')

In [391]:
df = df.drop(columns=["season_x","season_y","start_date","dl_applied","venue_y","result","date","team1","team2"])

In [392]:
df.columns

Index(['match_id', 'venue_x', 'innings', 'ball', 'batting_team',
       'bowling_team', 'striker', 'non_striker', 'bowler', 'runs_off_bat',
       'extras', 'wides', 'noballs', 'byes', 'legbyes', 'wicket_type',
       'cricsheet_id', 'toss_winner', 'toss_decision', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'umpire1', 'umpire2', 'umpire3'],
      dtype='object')

In [393]:
df

,match_id,venue_x,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,...,cricsheet_id,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,player_of_match,umpire1,umpire2,umpire3
0,1370353,"Narendra Modi Stadium, Ahmedabad",1,0.1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,DL Chahar,0,...,1370353,Chennai Super Kings,field,Chennai Super Kings,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
1,1370353,"Narendra Modi Stadium, Ahmedabad",1,0.2,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,DL Chahar,0,...,1370353,Chennai Super Kings,field,Chennai Super Kings,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
2,1370353,"Narendra Modi Stadium, Ahmedabad",1,0.3,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,DL Chahar,1,...,1370353,Chennai Super Kings,field,Chennai Super Kings,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
3,1370353,"Narendra Modi Stadium, Ahmedabad",1,0.4,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,DL Chahar,1,...,1370353,Chennai Super Kings,field,Chennai Super Kings,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
4,1370353,"Narendra Modi Stadium, Ahmedabad",1,0.5,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,DL Chahar,1,...,1370353,Chennai Super Kings,field,Chennai Super Kings,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243812,335982,M Chinnaswamy Stadium,2,14.5,Royal Challengers Bangalore,Kolkata Knight Riders,P Kumar,SB Joshi,I Sharma,0,...,335982,Royal Challengers Bangalore,field,Kolkata Knight Riders,140,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba
243813,335982,M Chinnaswamy Stadium,2,14.6,Royal Challengers Bangalore,Kolkata Knight Riders,SB Joshi,P Kumar,I Sharma,1,...,335982,Royal Challengers Bangalore,field,Kolkata Knight Riders,140,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba
243814,335982,M Chinnaswamy Stadium,2,14.7,Royal Challengers Bangalore,Kolkata Knight Riders,P Kumar,SB Joshi,I Sharma,0,...,335982,Royal Challengers Bangalore,field,Kolkata Knight Riders,140,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba
243815,335982,M Chinnaswamy Stadium,2,15.1,Royal Challengers Bangalore,Kolkata Knight Riders,SB Joshi,P Kumar,LR Shukla,0,...,335982,Royal Challengers Bangalore,field,Kolkata Knight Riders,140,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba
243816,335982,M Chinnaswamy Stadium,2,15.2,Royal Challengers Bangalore,Kolkata Knight Riders,SB Joshi,P Kumar,LR Shukla,0,...,335982,Royal Challengers Bangalore,field,Kolkata Knight Riders,140,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba

In [394]:
df.venue_x.value_counts()

venue_x
Eden Gardens                                                             17988
Wankhede Stadium                                                         17591
M Chinnaswamy Stadium                                                    14907
Feroz Shah Kotla                                                         13950
MA Chidambaram Stadium, Chepauk                                          11760
Rajiv Gandhi International Stadium, Uppal                                11604
Dubai International Cricket Stadium                                      11229
Sawai Mansingh Stadium                                                   11150
Wankhede Stadium, Mumbai                                                  9227
Punjab Cricket Association Stadium, Mohali                                8266
Sheikh Zayed Stadium                                                      6925
Sharjah Cricket Stadium                                                   6672
Maharashtra Cricket Association Stadium                                   5294
Dr DY Patil Sports Academy, Mumbai                                        4905
MA Chidambaram Stadium, Chepauk, Chennai                                  4671
Brabourne Stadium, Mumbai                                                 4057
Dr DY Patil Sports Academy                                                3993
Narendra Modi Stadium, Ahmedabad                                          3830
Subrata Roy Sahara Stadium                                                3825
Kingsmead                                                                 3643
Rajiv Gandhi International Stadium                                        3609
M.Chinnaswamy Stadium                                                     3494
Arun Jaitley Stadium                                                      3356
Maharashtra Cricket Association Stadium, Pune                             3120
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                       3037
Sardar Patel Stadium, Motera                                              2893
SuperSport Park                                                           2866
Arun Jaitley Stadium, Delhi                                               2711
Punjab Cricket Association IS Bindra Stadium, Mohali                      2574
Brabourne Stadium                                                         2469
Punjab Cricket Association IS Bindra Stadium                              2429
Saurashtra Cricket Association Stadium                                    2381
Eden Gardens, Kolkata                                                     2189
Himachal Pradesh Cricket Association Stadium                              2159
MA Chidambaram Stadium                                                    2130
Holkar Cricket Stadium                                                    1965
New Wanderers Stadium                                                     1940
Zayed Cricket Stadium, Abu Dhabi                                          1874
M Chinnaswamy Stadium, Bengaluru                                          1730
Rajiv Gandhi International Stadium, Uppal, Hyderabad                      1710
Barabati Stadium                                                          1695
St George's Park                                                          1677
JSCA International Stadium Complex                                        1671
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow     1583
Newlands                                                                  1539
Shaheed Veer Narayan Singh International Stadium                          1431
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh          1207
Nehru Stadium                                                             1155
Sawai Mansingh Stadium, Jaipur                                            1127
Green Park                                                                 921
Vidarbha Cricket Association Stadium, Jamtha                               742
De Beers Diamond Oval                                                      726
Buffalo Park                                                               715
Barsapara Cricket Stadium, Guwahati                                        504
Himachal Pradesh Cricket Association Stadium, Dharamsala                   501
OUTsurance Oval                                                            500
Name: count, dtype: int64

In [395]:
# Create a dictionary to map the full venue names to the simplified versions
venue_mapping = {
    'Eden Gardens': 'Eden Gardens',
    'Eden Gardens, Kolkata': 'Eden Gardens',
    'Wankhede Stadium': 'Wankhede Stadium',
    'Wankhede Stadium, Mumbai': 'Wankhede Stadium',
    'M Chinnaswamy Stadium': 'M Chinnaswamy Stadium',
    'M.Chinnaswamy Stadium': 'M Chinnaswamy Stadium',
    'M Chinnaswamy Stadium, Bengaluru': 'M Chinnaswamy Stadium',
    'MA Chidambaram Stadium, Chepauk': 'MA Chidambaram Stadium',
    'MA Chidambaram Stadium': 'MA Chidambaram Stadium',
    'MA Chidambaram Stadium, Chepauk, Chennai': 'MA Chidambaram Stadium',
    'Rajiv Gandhi International Stadium, Uppal': 'Rajiv Gandhi International Stadium',
    'Rajiv Gandhi International Stadium': 'Rajiv Gandhi International Stadium',
    'Rajiv Gandhi International Stadium, Uppal, Hyderabad': 'Rajiv Gandhi International Stadium',
    'Punjab Cricket Association Stadium, Mohali': 'Punjab Cricket Association Stadium',
    'Punjab Cricket Association IS Bindra Stadium, Mohali': 'Punjab Cricket Association Stadium',
    'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh': 'Punjab Cricket Association Stadium',
    'Dr DY Patil Sports Academy, Mumbai': 'Dr DY Patil Sports Academy',
    'Dr DY Patil Sports Academy': 'Dr DY Patil Sports Academy',
    'Narendra Modi Stadium, Ahmedabad': 'Narendra Modi Stadium',
    'Sardar Patel Stadium, Motera': 'Narendra Modi Stadium',
    'Brabourne Stadium, Mumbai': 'Brabourne Stadium',
    'Brabourne Stadium': 'Brabourne Stadium'
}

# Replace the venue names using the mapping dictionary
df['venue_x'] = df['venue_x'].map(venue_mapping).fillna(df['venue_x'])

In [396]:
df.isnull().sum()

match_id              0
venue_x               0
innings               0
ball                  0
batting_team          0
bowling_team          0
striker               0
non_striker           0
bowler                0
runs_off_bat          0
extras                0
wides                 0
noballs               0
byes                  0
legbyes               0
wicket_type           0
cricsheet_id          0
toss_winner           0
toss_decision         0
winner             4124
win_by_runs           0
win_by_wickets        0
player_of_match     490
umpire1               0
umpire2               0
umpire3             689
dtype: int64

In [397]:
df.venue_x.value_counts()

venue_x
Wankhede Stadium                                                         26818
Eden Gardens                                                             20177
M Chinnaswamy Stadium                                                    20131
MA Chidambaram Stadium                                                   18561
Rajiv Gandhi International Stadium                                       16923
Feroz Shah Kotla                                                         13950
Punjab Cricket Association Stadium                                       12047
Dubai International Cricket Stadium                                      11229
Sawai Mansingh Stadium                                                   11150
Dr DY Patil Sports Academy                                                8898
Sheikh Zayed Stadium                                                      6925
Narendra Modi Stadium                                                     6723
Sharjah Cricket Stadium                                                   6672
Brabourne Stadium                                                         6526
Maharashtra Cricket Association Stadium                                   5294
Subrata Roy Sahara Stadium                                                3825
Kingsmead                                                                 3643
Arun Jaitley Stadium                                                      3356
Maharashtra Cricket Association Stadium, Pune                             3120
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                       3037
SuperSport Park                                                           2866
Arun Jaitley Stadium, Delhi                                               2711
Punjab Cricket Association IS Bindra Stadium                              2429
Saurashtra Cricket Association Stadium                                    2381
Himachal Pradesh Cricket Association Stadium                              2159
Holkar Cricket Stadium                                                    1965
New Wanderers Stadium                                                     1940
Zayed Cricket Stadium, Abu Dhabi                                          1874
Barabati Stadium                                                          1695
St George's Park                                                          1677
JSCA International Stadium Complex                                        1671
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow     1583
Newlands                                                                  1539
Shaheed Veer Narayan Singh International Stadium                          1431
Nehru Stadium                                                             1155
Sawai Mansingh Stadium, Jaipur                                            1127
Green Park                                                                 921
Vidarbha Cricket Association Stadium, Jamtha                               742
De Beers Diamond Oval                                                      726
Buffalo Park                                                               715
Barsapara Cricket Stadium, Guwahati                                        504
Himachal Pradesh Cricket Association Stadium, Dharamsala                   501
OUTsurance Oval                                                            500
Name: count, dtype: int64

In [398]:
import pandas as pd

def convert_over_ball_to_ball_number(over_ball):
    """
    Converts a float in the format 'over.ball' to a ball number.
    Example: 0.1 -> 1, 5.6 -> 36
    """
    if pd.isna(over_ball):
        return None
    over = int(over_ball)
    ball = int((over_ball - over) * 10)
    return over * 6 + ball

# Assuming your DataFrame is named 'df' and the column is named 'ball'
df['ball_number'] = df['ball'].apply(convert_over_ball_to_ball_number)
df = df.drop(columns=["ball"])

In [399]:
df.head()

,match_id,venue_x,innings,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,...,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,player_of_match,umpire1,umpire2,umpire3,ball_number
0,1370353,Narendra Modi Stadium,1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,DL Chahar,0,0,...,Chennai Super Kings,field,Chennai Super Kings,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,1
1,1370353,Narendra Modi Stadium,1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,DL Chahar,0,0,...,Chennai Super Kings,field,Chennai Super Kings,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,2
2,1370353,Narendra Modi Stadium,1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,DL Chahar,1,0,...,Chennai Super Kings,field,Chennai Super Kings,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,3
3,1370353,Narendra Modi Stadium,1,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,DL Chahar,1,0,...,Chennai Super Kings,field,Chennai Super Kings,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,4
4,1370353,Narendra Modi Stadium,1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,DL Chahar,1,0,...,Chennai Super Kings,field,Chennai Super Kings,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,5

In [400]:
df.batting_team.value_counts()

batting_team
Mumbai Indians                 29751
Royal Challengers Bangalore    28205
Kolkata Knight Riders          27920
Chennai Super Kings            26932
Rajasthan Royals               24410
Kings XI Punjab                22646
Sunrisers Hyderabad            19924
Delhi Daredevils               18786
Delhi Capitals                  9305
Deccan Chargers                 9034
Pune Warriors                   5443
Punjab Kings                    5140
Gujarat Titans                  4021
Lucknow Super Giants            3672
Gujarat Lions                   3566
Rising Pune Supergiant          1900
Kochi Tuskers Kerala            1582
Rising Pune Supergiants         1580
Name: count, dtype: int64

In [401]:
# Create a dictionary to map the batting team names to abbreviations
team_mapping = {
    'Mumbai Indians': 'MI',
    'Royal Challengers Bangalore': 'RCB',
    'Kolkata Knight Riders': 'KKR',
    'Chennai Super Kings': 'CSK',
    'Rajasthan Royals': 'RR',
    'Kings XI Punjab': 'KXIP',
    'Sunrisers Hyderabad': 'SRH',
    'Delhi Daredevils': 'DD',
    'Delhi Capitals': 'DC',
    'Deccan Chargers': 'DC',
    'Pune Warriors': 'PW',
    'Punjab Kings': 'PBKS',
    'Gujarat Titans': 'GT',
    'Lucknow Super Giants': 'LSG',
    'Gujarat Lions': 'GL',
    'Rising Pune Supergiant': 'RPS',
    'Kochi Tuskers Kerala': 'KTK',
    'Rising Pune Supergiants': 'RPS'
}

# Assuming your DataFrame is named 'df' and the column is named 'batting_team'
df['batting_team'] = df['batting_team'].map(team_mapping).fillna(df["batting_team"])
df["bowling_team"] = df["bowling_team"].map(team_mapping).fillna(df["bowling_team"])
df["toss_winner"] = df["toss_winner"].map(team_mapping).fillna(df["toss_winner"])
df["winner"] = df["winner"].map(team_mapping).fillna(df["winner"])

In [402]:
df.isnull().sum()

match_id              0
venue_x               0
innings               0
batting_team          0
bowling_team          0
striker               0
non_striker           0
bowler                0
runs_off_bat          0
extras                0
wides                 0
noballs               0
byes                  0
legbyes               0
wicket_type           0
cricsheet_id          0
toss_winner           0
toss_decision         0
winner             4124
win_by_runs           0
win_by_wickets        0
player_of_match     490
umpire1               0
umpire2               0
umpire3             689
ball_number           0
dtype: int64

In [403]:
df.isnull().sum()

match_id              0
venue_x               0
innings               0
batting_team          0
bowling_team          0
striker               0
non_striker           0
bowler                0
runs_off_bat          0
extras                0
wides                 0
noballs               0
byes                  0
legbyes               0
wicket_type           0
cricsheet_id          0
toss_winner           0
toss_decision         0
winner             4124
win_by_runs           0
win_by_wickets        0
player_of_match     490
umpire1               0
umpire2               0
umpire3             689
ball_number           0
dtype: int64

In [404]:
null_rows = df[df['umpire3'].isnull()]
null_rows["match_id"].unique()

array([1254088,  598021,  501251])

In [405]:
df

,match_id,venue_x,innings,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,...,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,player_of_match,umpire1,umpire2,umpire3,ball_number
0,1370353,Narendra Modi Stadium,1,GT,CSK,WP Saha,Shubman Gill,DL Chahar,0,0,...,CSK,field,CSK,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,1
1,1370353,Narendra Modi Stadium,1,GT,CSK,WP Saha,Shubman Gill,DL Chahar,0,0,...,CSK,field,CSK,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,2
2,1370353,Narendra Modi Stadium,1,GT,CSK,WP Saha,Shubman Gill,DL Chahar,1,0,...,CSK,field,CSK,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,3
3,1370353,Narendra Modi Stadium,1,GT,CSK,Shubman Gill,WP Saha,DL Chahar,1,0,...,CSK,field,CSK,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,4
4,1370353,Narendra Modi Stadium,1,GT,CSK,WP Saha,Shubman Gill,DL Chahar,1,0,...,CSK,field,CSK,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243812,335982,M Chinnaswamy Stadium,2,RCB,KKR,P Kumar,SB Joshi,I Sharma,0,1,...,RCB,field,KKR,140,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,89
243813,335982,M Chinnaswamy Stadium,2,RCB,KKR,SB Joshi,P Kumar,I Sharma,1,0,...,RCB,field,KKR,140,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,89
243814,335982,M Chinnaswamy Stadium,2,RCB,KKR,P Kumar,SB Joshi,I Sharma,0,0,...,RCB,field,KKR,140,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,90
243815,335982,M Chinnaswamy Stadium,2,RCB,KKR,SB Joshi,P Kumar,LR Shukla,0,1,...,RCB,field,KKR,140,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,90
243816,335982,M Chinnaswamy Stadium,2,RCB,KKR,SB Joshi,P Kumar,LR Shukla,0,0,...,RCB,field,KKR,140,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,91

In [406]:
df.isnull().sum()

match_id              0
venue_x               0
innings               0
batting_team          0
bowling_team          0
striker               0
non_striker           0
bowler                0
runs_off_bat          0
extras                0
wides                 0
noballs               0
byes                  0
legbyes               0
wicket_type           0
cricsheet_id          0
toss_winner           0
toss_decision         0
winner             4124
win_by_runs           0
win_by_wickets        0
player_of_match     490
umpire1               0
umpire2               0
umpire3             689
ball_number           0
dtype: int64

In [407]:
import pandas as pd

def get_umpire3_fill_value(df):
    """
    Returns the most frequent non-null value in the 'umpire3' column
    that is different from 'umpire1' and 'umpire2'.
    """
    # Get the value counts of non-null values in 'umpire3'
    umpire3_counts = df['umpire3'].value_counts(dropna=True)

    # Iterate over the value counts to find the first value that is different from 'umpire1' and 'umpire2'
    for umpire, count in umpire3_counts.items():
        if (df['umpire1'] != umpire).any() and (df['umpire2'] != umpire).any():
            return umpire

    # If no suitable value is found, return None
    return None

# Usage
# Assuming your DataFrame is named 'df'
fill_value = get_umpire3_fill_value(df)

if fill_value is not None:
    df['umpire3'] = df['umpire3'].fillna(fill_value)
else:
    print("No suitable value found for filling 'umpire3'")

In [408]:
df.isnull().sum()

match_id              0
venue_x               0
innings               0
batting_team          0
bowling_team          0
striker               0
non_striker           0
bowler                0
runs_off_bat          0
extras                0
wides                 0
noballs               0
byes                  0
legbyes               0
wicket_type           0
cricsheet_id          0
toss_winner           0
toss_decision         0
winner             4124
win_by_runs           0
win_by_wickets        0
player_of_match     490
umpire1               0
umpire2               0
umpire3               0
ball_number           0
dtype: int64

In [409]:
df

,match_id,venue_x,innings,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,...,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,player_of_match,umpire1,umpire2,umpire3,ball_number
0,1370353,Narendra Modi Stadium,1,GT,CSK,WP Saha,Shubman Gill,DL Chahar,0,0,...,CSK,field,CSK,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,1
1,1370353,Narendra Modi Stadium,1,GT,CSK,WP Saha,Shubman Gill,DL Chahar,0,0,...,CSK,field,CSK,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,2
2,1370353,Narendra Modi Stadium,1,GT,CSK,WP Saha,Shubman Gill,DL Chahar,1,0,...,CSK,field,CSK,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,3
3,1370353,Narendra Modi Stadium,1,GT,CSK,Shubman Gill,WP Saha,DL Chahar,1,0,...,CSK,field,CSK,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,4
4,1370353,Narendra Modi Stadium,1,GT,CSK,WP Saha,Shubman Gill,DL Chahar,1,0,...,CSK,field,CSK,0,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243812,335982,M Chinnaswamy Stadium,2,RCB,KKR,P Kumar,SB Joshi,I Sharma,0,1,...,RCB,field,KKR,140,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,89
243813,335982,M Chinnaswamy Stadium,2,RCB,KKR,SB Joshi,P Kumar,I Sharma,1,0,...,RCB,field,KKR,140,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,89
243814,335982,M Chinnaswamy Stadium,2,RCB,KKR,P Kumar,SB Joshi,I Sharma,0,0,...,RCB,field,KKR,140,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,90
243815,335982,M Chinnaswamy Stadium,2,RCB,KKR,SB Joshi,P Kumar,LR Shukla,0,1,...,RCB,field,KKR,140,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,90
243816,335982,M Chinnaswamy Stadium,2,RCB,KKR,SB Joshi,P Kumar,LR Shukla,0,0,...,RCB,field,KKR,140,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,91

In [410]:
# Drop rows where 'umpire3' has null values, modifying the DataFrame in-place
df.dropna(subset=['winner'], inplace=True)

In [411]:
df.isnull().sum() > 0

match_id           False
venue_x            False
innings            False
batting_team       False
bowling_team       False
striker            False
non_striker        False
bowler             False
runs_off_bat       False
extras             False
wides              False
noballs            False
byes               False
legbyes            False
wicket_type        False
cricsheet_id       False
toss_winner        False
toss_decision      False
winner             False
win_by_runs        False
win_by_wickets     False
player_of_match    False
umpire1            False
umpire2            False
umpire3            False
ball_number        False
dtype: bool

In [412]:
df.columns

Index(['match_id', 'venue_x', 'innings', 'batting_team', 'bowling_team',
       'striker', 'non_striker', 'bowler', 'runs_off_bat', 'extras', 'wides',
       'noballs', 'byes', 'legbyes', 'wicket_type', 'cricsheet_id',
       'toss_winner', 'toss_decision', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'umpire1', 'umpire2', 'umpire3',
       'ball_number'],
      dtype='object')

In [413]:
# Create a new column by combining match_id and innings
df['match_innings'] = df['match_id'].astype(str) + '_' + df['innings'].astype(str)

# Group by the new column and calculate cumulative sum
df['current_runs'] = df.groupby('match_innings')['runs_off_bat'].cumsum()

In [414]:
# Create a temporary column to indicate if a wicket fell
df['wicket_fell'] = df['wicket_type'].apply(lambda x: 1 if x != 'none' else 0)

# Group by match_id and innings, and calculate the cumulative sum of wickets_fell
df['wickets_down'] = df.groupby(['match_id', 'innings'])['wicket_fell'].cumsum()

# Drop the temporary wicket_fell column
df.drop('wicket_fell', axis=1, inplace=True)

In [415]:
# Calculate the run rate
df['run_rate'] = (df['current_runs'] / df['ball_number']) * 6

In [416]:
df

,match_id,venue_x,innings,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,...,win_by_wickets,player_of_match,umpire1,umpire2,umpire3,ball_number,match_innings,current_runs,wickets_down,run_rate
0,1370353,Narendra Modi Stadium,1,GT,CSK,WP Saha,Shubman Gill,DL Chahar,0,0,...,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,1,1370353_1,0,0,0.000000
1,1370353,Narendra Modi Stadium,1,GT,CSK,WP Saha,Shubman Gill,DL Chahar,0,0,...,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,2,1370353_1,0,0,0.000000
2,1370353,Narendra Modi Stadium,1,GT,CSK,WP Saha,Shubman Gill,DL Chahar,1,0,...,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,3,1370353_1,1,0,2.000000
3,1370353,Narendra Modi Stadium,1,GT,CSK,Shubman Gill,WP Saha,DL Chahar,1,0,...,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,4,1370353_1,2,0,3.000000
4,1370353,Narendra Modi Stadium,1,GT,CSK,WP Saha,Shubman Gill,DL Chahar,1,0,...,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,5,1370353_1,3,0,3.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243812,335982,M Chinnaswamy Stadium,2,RCB,KKR,P Kumar,SB Joshi,I Sharma,0,1,...,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,89,335982_2,62,9,4.179775
243813,335982,M Chinnaswamy Stadium,2,RCB,KKR,SB Joshi,P Kumar,I Sharma,1,0,...,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,89,335982_2,63,9,4.247191
243814,335982,M Chinnaswamy Stadium,2,RCB,KKR,P Kumar,SB Joshi,I Sharma,0,0,...,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,90,335982_2,63,9,4.200000
243815,335982,M Chinnaswamy Stadium,2,RCB,KKR,SB Joshi,P Kumar,LR Shukla,0,1,...,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,90,335982_2,63,9,4.200000
243816,335982,M Chinnaswamy Stadium,2,RCB,KKR,SB Joshi,P Kumar,LR Shukla,0,0,...,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,91,335982_2,63,10,4.153846

In [417]:
# Create a DataFrame for the first innings
innings_1 = df[df['innings'] == 1]

# Create a DataFrame for the second innings
innings_2 = df[df['innings'] == 2]

In [418]:
df

,match_id,venue_x,innings,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,...,win_by_wickets,player_of_match,umpire1,umpire2,umpire3,ball_number,match_innings,current_runs,wickets_down,run_rate
0,1370353,Narendra Modi Stadium,1,GT,CSK,WP Saha,Shubman Gill,DL Chahar,0,0,...,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,1,1370353_1,0,0,0.000000
1,1370353,Narendra Modi Stadium,1,GT,CSK,WP Saha,Shubman Gill,DL Chahar,0,0,...,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,2,1370353_1,0,0,0.000000
2,1370353,Narendra Modi Stadium,1,GT,CSK,WP Saha,Shubman Gill,DL Chahar,1,0,...,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,3,1370353_1,1,0,2.000000
3,1370353,Narendra Modi Stadium,1,GT,CSK,Shubman Gill,WP Saha,DL Chahar,1,0,...,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,4,1370353_1,2,0,3.000000
4,1370353,Narendra Modi Stadium,1,GT,CSK,WP Saha,Shubman Gill,DL Chahar,1,0,...,5,DP Conway,Nitin Menon,RJ Tucker,KN Ananthapadmanabhan,5,1370353_1,3,0,3.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243812,335982,M Chinnaswamy Stadium,2,RCB,KKR,P Kumar,SB Joshi,I Sharma,0,1,...,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,89,335982_2,62,9,4.179775
243813,335982,M Chinnaswamy Stadium,2,RCB,KKR,SB Joshi,P Kumar,I Sharma,1,0,...,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,89,335982_2,63,9,4.247191
243814,335982,M Chinnaswamy Stadium,2,RCB,KKR,P Kumar,SB Joshi,I Sharma,0,0,...,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,90,335982_2,63,9,4.200000
243815,335982,M Chinnaswamy Stadium,2,RCB,KKR,SB Joshi,P Kumar,LR Shukla,0,1,...,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,90,335982_2,63,9,4.200000
243816,335982,M Chinnaswamy Stadium,2,RCB,KKR,SB Joshi,P Kumar,LR Shukla,0,0,...,0,BB McCullum,Asad Rauf,RE Koertzen,AM Saheba,91,335982_2,63,10,4.153846

In [419]:
with open("cleaned.csv","w") as f:
    df.to_csv(f)

In [420]:
df.columns

Index(['match_id', 'venue_x', 'innings', 'batting_team', 'bowling_team',
       'striker', 'non_striker', 'bowler', 'runs_off_bat', 'extras', 'wides',
       'noballs', 'byes', 'legbyes', 'wicket_type', 'cricsheet_id',
       'toss_winner', 'toss_decision', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'umpire1', 'umpire2', 'umpire3',
       'ball_number', 'match_innings', 'current_runs', 'wickets_down',
       'run_rate'],
      dtype='object')

# Categorise Columns

In [421]:
num_cols = list(df.select_dtypes(include=['int', 'float']).columns)
cat_cols = list(df.select_dtypes(exclude=['int', 'float']).columns)

In [422]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.base import BaseEstimator, TransformerMixin

# Custom IQR Removal Transformer

In [423]:
class Outlier_Remover(BaseEstimator, TransformerMixin):
    
    def __init__(self, action='keep'): 
        self.action = action
        
    def fit(self, X, y=None):
        self.median_ = np.median(X, axis=0)
        return self
    
    def transform(self, X):
        Q1 = np.percentile(X, 25, axis=0)
        Q3 = np.percentile(X, 75, axis=0) 
        
        IQR = Q3 - Q1

        lower = Q1 - 1.5*IQR
        upper = Q3 + 1.5*IQR
        
        outlier_mask = (X < lower) | (X > upper)
        
        if self.action == 'drop':
            return X[~outlier_mask]
        else:
            for i in range(X.shape[1]):
                X[:, i][outlier_mask[:, i]] = self.median_[i]
            return X

# Define Pipeline's for both type of columns

In [424]:
cat_preprocessor = Pipeline(steps=[
    ("cat_null_handler",SimpleImputer(missing_values=np.nan,strategy="most_frequent")),
    ("cat_enocder",OrdinalEncoder()),
])


num_preprocessor = Pipeline(steps=[
    ("num_null_handler",SimpleImputer(missing_values=np.nan,strategy='median')),
    ("num_outlier_remover",Outlier_Remover(action="keep")),
    ("num_scaler",StandardScaler()),
])

# Preprocess data with Pipeline

In [425]:
df[num_cols] = num_preprocessor.fit_transform(df[num_cols])
df[cat_cols] = cat_preprocessor.fit_transform(df[cat_cols])
df.head()

,match_id,venue_x,innings,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,...,win_by_wickets,player_of_match,umpire1,umpire2,umpire3,ball_number,match_innings,current_runs,wickets_down,run_rate
0,1.415477,23.0,-0.966513,4.0,0.0,617.0,554.0,124.0,-1.121212,0.0,...,0.524566,61.0,37.0,42.0,33.0,-1.684360,872.0,-1.532461,-1.191229,0.000935
1,1.415477,23.0,-0.966513,4.0,0.0,617.0,554.0,124.0,-1.121212,0.0,...,0.524566,61.0,37.0,42.0,33.0,-1.655015,872.0,-1.532461,-1.191229,0.000935
2,1.415477,23.0,-0.966513,4.0,0.0,617.0,554.0,124.0,0.570349,0.0,...,0.524566,61.0,37.0,42.0,33.0,-1.625670,872.0,-1.510941,-1.191229,0.000935
3,1.415477,23.0,-0.966513,4.0,0.0,561.0,608.0,124.0,0.570349,0.0,...,0.524566,61.0,37.0,42.0,33.0,-1.596324,872.0,-1.489420,-1.191229,-2.425067
4,1.415477,23.0,-0.966513,4.0,0.0,617.0,554.0,124.0,0.570349,0.0,...,0.524566,61.0,37.0,42.0,33.0,-1.566979,872.0,-1.467900,-1.191229,-2.071340

# Train Test Split

In [426]:
X = df.drop(columns=["winner"])
y = df.winner

In [427]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping

# Define the input shape
input_shape = X_train.shape[1]

# Create the model
model = Sequential()

# Add the input layer
model.add(Dense(512, activation='relu', input_shape=(input_shape,)))
model.add(BatchNormalization())
model.add(Dropout(0.3))

# Add hidden layers
model.add(Dense(1024, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.4))
model.add(Dense(2048, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(1024, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.4))
model.add(Dense(512, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.3))

# Add the output layer
output_units = len(np.unique(y_train))
model.add(Dense(output_units, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Define early stopping callback
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=128, validation_data=(X_test, y_test), callbacks=[early_stop])